version: '3.9'

services:
  db.postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres.db:/var/lib/postgresql/data
    restart: on-failure

#  redis:
#    image: redis:alpine
#    ports:
#      - '${REDIS_PORT}:6379'
#    command: >
#      --requirepass '${REDIS_PASSWORD}'
#    restart: on-failure

volumes:
  postgres.db: